version: '3.8'

services:
  product-service:
    build: ./product-service
    image: abrahamjose04/product-service:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - rabbitmq
    networks:
      - app-network

  inventory-service:
    build: ./inventory-service
    image: abrahamjose04/inventory-service:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - rabbitmq
    networks:
      - app-network

  client-service:
    build: ./client-service
    image: abrahamjose04/client-service:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - product-service
      - inventory-service
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
